import { COLLECTIONS } from "../../../../enums/collections.enum";

export enum CollaboratorRole {
  PI = "PI",
  CO_PI = "CO_PI",
  INVESTIGATOR = "INVESTIGATOR",
  ASSISTANT = "ASSISTANT",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  ADVISOR = "ADVISOR",
  COMMUNITY_PARTNER = "COMMUNITY_PARTNER",
}

export enum AssignmentType {
  PROJECT = COLLECTIONS.PROJECT,
  THEME = COLLECTIONS.PROJECT_THEMEM,
  PHASE = COLLECTIONS.PHASE
}