import fs from "fs";
import path from "path";
import puppeteer, { Browser, PDFOptions } from "puppeteer";

export interface PdfPageOptions {
    format?: PDFOptions["format"];
    landscape?: boolean;

    displayHeaderFooter?: boolean;

    headerTemplate?: string;
    footerTemplate?: string;

    margin?: PDFOptions["margin"];
}

export const PAGE_OPTIONS: Record<string, PdfPageOptions> = {
    agreement: {
        format: "A4",
        landscape: false,
        displayHeaderFooter: true,
        margin: {
            top: "30mm",
            bottom: "25mm",
            left: "18mm",
            right: "18mm",
        },
    },

    certificate: {
        format: "A4",
        landscape: true,
        displayHeaderFooter: false,
        margin: {
            top: "10mm",
            bottom: "10mm",
            left: "10mm",
            right: "10mm",
        },
    },
};

const RESOURCES = path.join(process.cwd(), "resources");

const LOGO_PATH = path.join(RESOURCES, "logo.png");

const logoBase64 = fs.existsSync(LOGO_PATH)
    ? fs.readFileSync(LOGO_PATH).toString("base64")
    : "";

const DEFAULT_HEADER_HTML = `
<div style="
    width: 100%;
    font-size: 10px;
    padding: 0 18mm;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid #000;
    font-family: 'Noto Sans Ethiopic', Arial, sans-serif;
    box-sizing: border-box;
">
    <div style="text-align: left;">
        <b>
            Research &amp; Development Directorate<br/>
            Wolkite University
        </b>
    </div>

    ${logoBase64
        ? `
            <img
                src="data:image/png;base64,${logoBase64}"
                style="height: 45px;"
            />
            `
        : ""
    }

    <div style="text-align: right;">
        <b>
            የምርምርና ቴክኖሎጂ ሽግግር ም/ፕሬዝዳንት <br/>
            ወልቂጤ ዩኒቨርሲቲ
        </b>
    </div>
</div>
`;

const DEFAULT_FOOTER_HTML = `
<div style="
    width: 100%;
    font-size: 9px;
    padding: 0 18mm;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid #000;
    font-family: Arial, sans-serif;
    box-sizing: border-box;
">
    <div>
        Email: vpresearch@wku.edu.et<br/>
        P.O.Box: 07
    </div>

    <div>
        <span class="pageNumber"></span>
        /
        <span class="totalPages"></span>
    </div>

    <div style="text-align: right;">
        Website: www.wku.edu.et<br/>
        Generated by WKU - IRPMS
    </div>
</div>
`;

export class PdfRenderer {

    private browser: Browser | null = null;

    private launching: Promise<Browser> | null = null;

    /**
     * Returns a shared Puppeteer browser instance.
     * Automatically relaunches when the browser crashes/disconnects.
     */
    private async getBrowser(): Promise<Browser> {

        if (this.browser?.connected) {
            return this.browser;
        }

        if (!this.launching) {

            this.launching = puppeteer
                .launch({
                    headless: true,
                    args: [
                        "--no-sandbox",
                        "--disable-setuid-sandbox",
                        "--disable-dev-shm-usage",
                    ],
                })
                .then((browser) => {

                    this.browser = browser;
                    this.launching = null;

                    return browser;
                })
                .catch((error) => {

                    this.launching = null;

                    throw error;
                });
        }

        return this.launching;
    }

    /**
     * Render HTML into a PDF.
     *
     * The HTML is normally generated from an HBS template.
     * Header/footer are PDF-level elements controlled here.
     */
    async render(
        html: string,
        options: PdfPageOptions = PAGE_OPTIONS.agreement
    ): Promise<Buffer> {

        const browser = await this.getBrowser();

        const page = await browser.newPage();

        try {

            /**
             * Prevent templates from accessing external
             * websites/resources.
             *
             * Data URLs are allowed because images can be
             * embedded directly into the generated document.
             */
            await page.setRequestInterception(true);

            page.on("request", (request) => {

                const url = request.url();

                if (
                    url.startsWith("data:") ||
                    url === "about:blank"
                ) {
                    request.continue();
                    return;
                }

                request.abort();
            });

            /**
             * Load generated HTML.
             */
            await page.setContent(html, {
                waitUntil: "load",
                timeout: 30_000,
            });

            const displayHeaderFooter =
                options.displayHeaderFooter ?? false;

            /**
             * Generate PDF.
             */
            const pdf = await page.pdf({

                format: options.format ?? "A4",

                landscape: options.landscape ?? false,

                printBackground: true,

                displayHeaderFooter: displayHeaderFooter,

                headerTemplate: displayHeaderFooter
                    ? options.headerTemplate ??
                    DEFAULT_HEADER_HTML
                    : "<span></span>",

                footerTemplate: displayHeaderFooter
                    ? options.footerTemplate ??
                    DEFAULT_FOOTER_HTML
                    : "<span></span>",

                margin: options.margin ??
                    (
                        displayHeaderFooter
                            ? {
                                top: "30mm",
                                bottom: "25mm",
                                left: "18mm",
                                right: "18mm",
                            }
                            : {
                                top: "10mm",
                                bottom: "10mm",
                                left: "10mm",
                                right: "10mm",
                            }
                    ),
            });

            /**
             * Newer Puppeteer versions return Uint8Array.
             */
            return Buffer.from(pdf);

        } finally {

            await page.close();
        }
    }

    /**
     * Close the shared browser.
     */
    async close(): Promise<void> {

        if (this.browser) {
            await this.browser.close();
            this.browser = null;
        }
    }
}