export enum COLLECTIONS {
  APPLICANT = "applicants",
  POSITION = "positions",
  ORGANIZATION = "organizations",
  THEME = "thms",
  EVALUATION = "evaluations",
  CALENDAR = "calendars",
  CALL = "calls",
  CALL_STAGE="callstages",
  GRANT = "grants",
  CONSTRAINT = "constraints",
  COMPOSITION = "compositions",
  USER = "users",
  ROLE = "roles",
  PERMISSION = "permissions",
  PROJECT = "projects",
  COLLABORATOR = "collaborators",
  PHASE = "phases",
  PROJECT_THEMEM = "prothemes",
  COLLABORATOR_ASSIGNMENT = "collaboratorassignments",
  PROJECT_STAGE = "projectstages",
  REVIEWER = "reviewers",
  RESULT = "results",
}