export enum COLLECTIONS {
  APPLICANT = "applicants",
  POSITION = "positions",
  ORGANIZATION = "organizations",
  EXPERIENCE = "experiences",
  THEME = "themes",
  EVALUATION = "evaluations",
  CRITERION = "criteria",
  OPTION = "options",
  CALENDAR = "calendars",
  CYCLE = "cycles",
  STAGE = "cyclestages",
  GRANT = "grants",
  CONSTRAINT = "constraints",
  //PROJECT_CONSTRAINT = "projectconstraints",
  COMPOSITION = "compositions",
  USER = "users",
  ROLE = "roles",
  PERMISSION = "permissions",
  PROJECT = "projects",
  COLLABORATOR = "collaborators",
  PHASE = "phases",
  PROJECT_THEMEM = "prothemes",
  COLLABORATOR_ASSIGNMENT = "collaboratorassignments",
  PROJECT_STAGE = "projectstages",
  REVIEWER = "reviewers",
  RESULT = "results",
}