export enum COLLECTIONS {
  APPLICANT = "applicants",
  POSITION = "positions",
  ORGANIZATION = "organizations",
  THEME = "themes",
  EVALUATION = "evaluations",
  CRITERION = "criteria",
  OPTION = "options",
  CALENDAR = "calendars",
  CALL = "calls",
  CALL_EVALUATION = "callevaluations",
  GRANT = "grants",
  CONSTRAINT = "constraints",
  COMPOSITION = "compositions",
  USER = "users",
  ROLE = "roles",
  PERMISSION = "permissions",
  PROJECT = "projects",
  COLLABORATOR = "collaborators",
  PHASE = "phases",
  PROJECT_THEMEM = "prothemes",
  COLLABORATOR_ASSIGNMENT = "collaboratorassignments",
  PROJECT_STAGE = "projectstages",
  REVIEWER = "reviewers",
  RESULT = "results",
}