export enum ProjectConstraintType {
    PARTICIPANT = "PARTICIPANT",
    PHASE_COUNT = "PHASE-COUNT",
    BUDGET_TOTAL = "BUDGET-TOTAL",
    TIME_TOTAL = "TIME-TOTAL",
    BUDGET_PHASE = "BUDGET-PHASE",
    TIME_PHASE = "TIME-PHASE",
    //ACTIVITIES_PHASE = "ACTIVITIES-PHASE",            
    THEME = "THEME",
    SUB_THEME = "SUB_THEME",
    FOCUS_AREA = "FOCUS_AREA",
    INDICATOR = "INDICATOR",
    PROJECT_TITLE = "PROJECT_TITLE",//characters
    PROJECT_SUMMARY = "PROJECT_SUMMARY",
}
//maxLength of title and summry: 200