export enum COLLECTIONS {
  PERMISSION = "permissions",
  ROLE = "roles",
  ACCOUNT = "accounts",

  ORGANIZATION = "organizations",
  USER = "users",
  PUBLICATION = "publications",
  SPECIALIZATION = "specializations",
  POSITION = "positions",
  EXPERIENCE = "experiences",
  ENROLLMENT = "enrollments",

  GRANT = "grants",
  GRANT_STAGE = "grantstages",
  CONSTRAINT = "constraints",
  COMPOSITION = "compositions",
  ELIGIBILITY_PROFILE = "eligibility_profiles",
  HISTORY_RULE = "history_rules",
  MEMBER_REQUIREMENT = "member_requirements",
  GRANT_ALLOCATION = "grantallocations",
  VERIFICATION_CONFIGURATION = "verification_confs",


  THEMATIC = "thematics",
  THEME = "themes",
  EVALUATION = "evaluations",
  TEMPLATE = "templates",
  CRITERION = "criteria",
  OPTION = "options",
  CALENDAR = "calendars",
  CALL = "calls",
  VERIFICATION = "verifications",
  STAGE = "stages",

  PROJECT = "projects",
  COLLABORATOR = "collaborators",
  PHASE = "phases",
  APPLICATION = "applications",
  //BREAKDOWN = "breakdowns",
  PHASE_DOCUMENT = "phasedocuments",
  //PROJECT_THEMEM = "prothemes",
  COLLABORATOR_ASSIGNMENT = "collaboratorassignments",
  REVIEWER = "reviewers",
  RESULT = "results",
}