export const ERROR_CODES = {
    USER_NOT_LEAD_PI: "USER_NOT_LEAD_PI",
    USER_NOT_REVIEWER: "USER_NOT_REVIEWER",

    // ---------- APPLICANT ----------
    APPLICANT_NOT_FOUND: "APPLICANT_NOT_FOUND",

    // ---------- CALL ----------
    CALL_NOT_FOUND: "CALL_NOT_FOUND",
    CALL_NOT_ACTIVE: "CALL_NOT_ACTIVE",
    CALL_NOT_PLANNED: "CALL_NOT_PLANNED",

    // ---------- STAGE ----------
    STAGE_NOT_FOUND: "STAGE_NOT_FOUND",
    STAGE_NOT_ACTIVE: "STAGE_NOT_ACTIVE",
    STAGE_DEADLINE_PASSED: "STAGE_DEADLINE_PASSED",

    // ---------- PROJECT DOC----------
    PROJECT_DOC_NOT_FOUND: "PROJECT_DOC_NOT_FOUND",
    PROJECT_DOC_NOT_ACCEPTED: "PROJECT_DOC_NOT_ACCEPTED",
    PROJECT_DOC_NOT_PENDING: "PROJECT_DOC_NOT_PENDING",

    // ---------- REVIEWER ----------
    REVIEWER_NOT_FOUND: "REVIEWER_NOT_FOUND",
    REVIEWER_NOT_PENDING: "REVIEWER_NOT_PENDING",
    REVIEWER_NOT_VERIFIED: "REVIEWER_NOT_VERIFIED",

    // ---------- PROJECT ----------
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_REJECTED: "PROJECT_REJECTED",


};

export type ErrorCode =
    typeof ERROR_CODES[keyof typeof ERROR_CODES];