export const ERROR_CODES = {
    //---------- GENERAL --------------
    UNAUTHORIZED: "UNAUTHORIZED",
    UNSUPPORTED_OPERTATION: "UNSUPPORTED_OPERTATION",
    INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    CURRENT_STATE_MISMATCH: "CURRENT_STATE_MISMATCH",
    STATE_OUT_OF_SYNC: "STATE_OUT_OF_SYNC",
    /*
    STATE_OUT_OF_SYNC: {
        code: "STATE_OUT_OF_SYNC",
        message: "The resource state has changed. Please refresh and try again."
    },
    */
    USER_NOT_LEAD_PI: "USER_NOT_LEAD_PI",
    USER_NOT_REVIEWER: "USER_NOT_REVIEWER",
    USER_NOT_COLLABORATOR: "USER_NOT_COLLABORATOR",

    // ---------- SETTING ----------
    SETTING_NOT_FOUND: "SETTING_NOT_FOUND",
    SETTING_FILE_SIZE_OUT_OF_RANGE: "File size must be between 1 and 100MB.",

    // ---------- ROLE ----------
    ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
    ROLE_IN_USE: "ROLE_IN_USE",

    // ---------- ACCOUNT ----------
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    ACCOUNT_SUSPENDED: "Account is suspended. Contact support.",
    ACCOUNT_LOCKED: "Account temporarily locked due to too many failed login attempts.",
    INVALID_CREDENTIALS: "Invalid credentials.",

    // ---------- USER ----------
    USER_NOT_FOUND: "USER_NOT_FOUND",

    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",



    // ---------- ORGANIZATION ----------
    ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
    DIRECTORATE_NOT_FOUND: "DIRECTORATE_NOT_FOUND",
    EXTERNAL_NOT_FOUND: "EXTERNAL_NOT_FOUND",
    PROGRAM_NOT_FOUND: "PROGRAM_NOT_FOUND",
    WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
    INVALID_WORKSPACE: "INVALID_WORKSPACE",
    ORGANIZATION_PARENT_NOT_FOUND: "ORGANIZATION_PARENT_NOT_FOUND",
    INVALID_PARENT_TYPE: "INVALID_PARENT_TYPE",
    INVALID_ORGANIZATION_TYPE: "INVALID_ORGANIZATION_TYPE",
    ORGANIZATION_HAS_CHILDREN: "ORGANIZATION_HAS_CHILDREN",
    ORGANIZATION_IN_USE: "ORGANIZATION_IN_USE",

    // ---------- SPECIALIZATION ----------
    SPECIALIZATION_NOT_FOUND: "SPECIALIZATION_NOT_FOUND",
    SPECIALIZATION_IN_USE: "SPECIALIZATION_IN_USE",

    // ---------- APPLICANT ----------
    APPLICANT_NOT_FOUND: "APPLICANT_NOT_FOUND",
    APPLICANT_HAS_PROJECTS: "APPLICANT_HAS_PROJECTS",

    // ---------- POSITION ----------
    POSITION_NOT_FOUND: "POSITION_NOT_FOUND",
    RANK_NOT_FOUND: "RANK_NOT_FOUND",
    RANK_ALREADY_EXISTS: "RANK_ALREADY_EXISTS",
    RANK_IN_USE: "RANK_IN_USE",

    // ---------- STUDNET ----------
    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
    STUDENT_ALREADY_EXISTS: "STUDENT_ALREADY_EXISTS",

    // ---------- PUBLICATION ----------
    PUBLICATION_NOT_FOUND: "PUBLICATION_NOT_FOUND",
    PUBLICATION_ALREADY_EXISTS: "PUBLICATION_ALREADY_EXISTS",

    // ---------- EXPERIENCE ----------
    EXPERIENCE_NOT_FOUND: "EXPERIENCE_NOT_FOUND",

    // ---------- CALENDAR ----------
    CALENDAR_NOT_FOUND: "CALENDAR_NOT_FOUND",
    CALENDAR_ALREADY_EXISTS: "CALENDAR_ALREADY_EXISTS",
    CALENDAR_INVALID_STATE_TRANSITION: "CALENDAR_INVALID_STATE_TRANSITION",
    CALENDAR_NOT_PLANNED: "CALENDAR_NOT_PLANNED",
    CALENDAR_NOT_ACTIVE: "CALENDAR_NOT_ACTIVE",

    // ---------- CALL ----------
    CALL_NOT_FOUND: "CALL_NOT_FOUND",
    CALL_NOT_ACTIVE: "CALL_NOT_ACTIVE",
    CALL_NOT_PLANNED: "CALL_NOT_PLANNED",
    CALL_ALREADY_EXISTS: "CALL_ALREADY_EXISTS",

    // ---------- STAGE ----------
    STAGE_NOT_FOUND: "STAGE_NOT_FOUND",
    STAGE_NOT_ACTIVE: "STAGE_NOT_ACTIVE",
    STAGE_NOT_PLANNED: "STAGE_NOT_PLANNED",
    STAGE_ALREADY_CLOSED: "STAGE_ALREADY_CLOSED",
    STAGE_ALREADY_EXISTS: "STAGE_ALREADY_EXISTS",
    STAGE_DEADLINE_PASSED: "STAGE_DEADLINE_PASSED",
    STAGE_DOCUMENT_ALREADY_EXISTS: "STAGE_DOCUMENT_ALREADY_EXISTS",

    // ---------- THEMATIC ----------
    THEMATIC_NOT_FOUND: "THEMATIC_NOT_FOUND",

    // ---------- THEME ----------
    THEME_NOT_FOUND: "THEME_NOT_FOUND",
    THEME_ALREADY_EXISTS: "THEME_ALREADY_EXISTS",
    INVALID_THEME_LEVEL: "INVALID_THEME_LEVEL",

    // ---------- EVALUATION ----------
    EVALUATION_NOT_FOUND: "EVALUATION_NOT_FOUND",

    // ---------- CRITERION ----------
    CRITERION_NOT_FOUND: "CRITERION_NOT_FOUND",
    CRITERION_ALREADY_EXISTS: "CRITERION_ALREADY_EXISTS",
    CRITERION_NOT_CLOSED: "CRITERION_NOT_CLOSED",
    INVALID_CRITERION_WEIGHT: "INVALID_CRITERION_WEIGHT",
    INCOMPELTE_CRITERIA: "INCOMPELTE_CRITERIA",

    // ---------- OPTION ----------
    OPTION_NOT_FOUND: "OPTION_NOT_FOUND",
    OPTION_ALREADY_EXISTS: "OPTION_ALREADY_EXISTS",
    INVALID_OPTION_WEIGHT: "INVALID_OPTION_WEIGHT",

    // ---------- GRANT ----------
    GRANT_NOT_FOUND: "GRANT_NOT_FOUND",


    // ---------- CONSTRAINT ----------    
    CONSTRAINT_NOT_FOUND: "CONSTRAINT_NOT_FOUND",
    CONSTRAINT_ALREADY_EXISTS: "CONSTRAINT_ALREADY_EXISTS",

    // ---------- COMPOSITION ----------    
    COMPOSITION_NOT_FOUND: "COMPOSITION_NOT_FOUND",
    PI_ALREADY_EXISTS_FOR_GRANT: "PI_ALREADY_EXISTS_FOR_GRANT",

    // ---------- PROJECT DOC----------
    DOC_NOT_FOUND: "DOC_NOT_FOUND",
    DOC_NOT_ACCEPTED: "DOC_NOT_ACCEPTED",
    DOC_NOT_SUBMITTED: "DOC_NOT_SUBMITTED",
    DOC_ALREADY_EXISTS: "DOC_ALREADY_EXISTS",
    DOC_SCORE_ALREADY_EXISTS: "DOC_SCORE_ALREADY_EXISTS",
    DOC_SCORE_NOT_EXISTS: "DOC_SCORE_DOES_NOT_EXISTS",
    NEXT_DOC_ALREADY_EXISTS: "NEXT_DOC_ALREADY_EXISTS",
    INVALID_DOC_STATUS: "INVALID_DOC_STATUS",
    // ---------- REVIEWER ----------
    REVIEWER_NOT_FOUND: "REVIEWER_NOT_FOUND",
    REVIEWER_NOT_PENDING: "REVIEWER_NOT_PENDING",
    REVIEWER_NOT_ACCEPTED: "REVIEWER_NOT_ACCEPTED",
    INVALID_REVIEWER: "INVALID_REVIEWER",
    INVALID_REVIEWER_WEIGHT: "INVALID_REVIEWER_WEIGHT",
    APPROVED_REVIEWER_ALREADY_EXISTS: "APPROVED_REVIEWER_ALREADY_EXISTS",
    REVIEWER_ALREADY_EXISTS: "REVIEWER_ALREADY_EXISTS",
    // ---------- RESULT ----------
    RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
    RESULT_ALREADY_EXISTS: "RESULT_ALREADY_EXISTS",
    // ---------- PROJECT ----------
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_REJECTED: "PROJECT_REJECTED",
    INVALID_PROJECT_STATUS: "INVALID_PROJECT_STATUS",
    PROJECT_NOT_PENDING: "PROJECT_NOT_PENDING",
    PROJECT_NOT_GRANTED: "PROJECT_NOT_GRANTED",
    PROJECT_NOT_IN_NEGOTIATION: "PROJECT_NOT_IN_NEGOTIATION",
    // ---------- COLLABORATOR ----------
    COLLABORATOR_NOT_FOUND: "COLLABORATOR_NOT_FOUND",
    COLLABORATOR_ALREADY_EXISTS: "COLLABORATOR_ALREADY_EXISTS",
    COLLABORATOR_NOT_PENDING: "COLLABORATOR_NOT_PENDING",
    COLLABORATORS_NOT_FULLY_VERIFIED: "COLLABORATORS_NOT_FULLY_VERIFIED",

    // ---------- PROJECT_THEME ----------
    PROJECT_THEME_NOT_FOUND: "PROJECT_THEME_NOT_FOUND",
    PROJECT_THEME_ALREADY_EXISTS: "PROJECT_THEME_ALREADY_EXISTS",

    // ---------- PHASE ----------
    PHASE_NOT_FOUND: "PHASE_NOT_FOUND",
    PHASE_NOT_ACTIVE: "PHASE_NOT_ACTIVE",
    PHASE_NOT_PROPOSED: "PHASE_NOT_PROPOSED",
    PHASE_ALREADY_EXISTS: "PHASE_ALREADY_EXISTS",
    PHASES_NOT_FULLY_APPROVED: "PHASES_NOT_FULLY_APPROVED",

    // ---------- PHASE_DOCUMENT ----------
    PHASE_DOCUMENT_NOT_FOUND: "PHASE_DOCUMENT_NOT_FOUND"

};

export type ErrorCode =
    typeof ERROR_CODES[keyof typeof ERROR_CODES];