export const ERROR_CODES = {

    //---------- GENERAL --------------
    INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",

    USER_NOT_LEAD_PI: "USER_NOT_LEAD_PI",
    USER_NOT_REVIEWER: "USER_NOT_REVIEWER",
    USER_NOT_COLLABORATOR: "USER_NOT_COLLABORATOR",
    USER_NOT_FOUND: "USER_NOT_FOUND",

    // ---------- ORGANIZATION ----------
    ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
    DIRECTORATE_NOT_FOUND: "DIRECTORATE_NOT_FOUND",
    PROGRAM_NOT_FOUND: "PROGRAM_NOT_FOUND",
    INVALID_ORGANIZATION_TYPE: "INVALID_ORGANIZATION_TYPE",

    // ---------- APPLICANT ----------
    APPLICANT_NOT_FOUND: "APPLICANT_NOT_FOUND",

    // ---------- STUDNET ----------
    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
    STUDENT_ALREADY_EXISTS: "STUDENT_ALREADY_EXISTS",

    // ---------- PUBLICATION ----------
    PUBLICATION_NOT_FOUND: "PUBLICATION_NOT_FOUND",
    PUBLICATION_ALREADY_EXISTS: "PUBLICATION_ALREADY_EXISTS",

    // ---------- EXPERIENCE ----------
    EXPERIENCE_NOT_FOUND: "EXPERIENCE_NOT_FOUND",

    // ---------- CALENDAR ----------
    CALENDAR_NOT_FOUND: "CALENDAR_NOT_FOUND",
    CALENDAR_ALREADY_EXISTS: "CALENDAR_ALREADY_EXISTS",
    CALENDAR_INVALID_STATE_TRANSITION: "CALENDAR_INVALID_STATE_TRANSITION",
    CALENDAR_NOT_PLANNED: "CALENDAR_NOT_PLANNED",
    CALENDAR_NOT_ACTIVE: "CALENDAR_NOT_ACTIVE",
    CALENDAR_HAS_CALLS: "CALENDAR_HAS_CALLS",

    // ---------- CALL ----------
    CALL_NOT_FOUND: "CALL_NOT_FOUND",
    CALL_NOT_ACTIVE: "CALL_NOT_ACTIVE",
    CALL_NOT_PLANNED: "CALL_NOT_PLANNED",
    CALL_STAGE_ALREADY_EXISTS: "CALL_STAGE_ALREADY_EXISTS",

    // ---------- STAGE ----------
    STAGE_NOT_FOUND: "STAGE_NOT_FOUND",
    STAGE_NOT_ACTIVE: "STAGE_NOT_ACTIVE",
    STAGE_NOT_PLANNED: "STAGE_NOT_PLANNED",
    STAGE_ALREADY_CLOSED: "STAGE_ALREADY_CLOSED",
    STAGE_DEADLINE_PASSED: "STAGE_DEADLINE_PASSED",
    STAGE_DOCUMENT_ALREADY_EXISTS: "STAGE_DOCUMENT_ALREADY_EXISTS",

    // ---------- THEMATIC ----------
    THEMATIC_NOT_FOUND: "THEMATIC_NOT_FOUND",

    // ---------- THEME ----------
    THEME_NOT_FOUND: "THEME_NOT_FOUND",

    // ---------- EVALUATION ----------
    EVALUATION_NOT_FOUND: "EVALUATION_NOT_FOUND",

    // ---------- CRITERION ----------
    CRITERION_NOT_FOUND: "CRITERION_NOT_FOUND",
    CRITERION_ALREADY_EXISTS: "CRITERION_ALREADY_EXISTS",
    INVALID_CRITERION_WEIGHT: "INVALID_CRITERION_WEIGHT",
    INCOMPELTE_CRITERIA: "INCOMPELTE_CRITERIA",

    // ---------- OPTION ----------
    OPTION_NOT_FOUND: "OPTION_NOT_FOUND",
    OPTION_ALREADY_EXISTS: "OPTION_ALREADY_EXISTS",

    // ---------- GRANT ----------
    GRANT_NOT_FOUND: "GRANT_NOT_FOUND",

    // ---------- PROJECT DOC----------
    DOC_NOT_FOUND: "DOC_NOT_FOUND",
    DOC_NOT_ACCEPTED: "DOC_NOT_ACCEPTED",
    DOC_NOT_SUBMITTED: "DOC_NOT_SUBMITTED",
    DOC_ALREADY_EXISTS: "DOC_ALREADY_EXISTS",
    DOC_SCORE_ALREADY_EXISTS: "DOC_SCORE_ALREADY_EXISTS",
    DOC_SCORE_NOT_EXISTS: "DOC_SCORE_DOES_NOT_EXISTS",
    NEXT_DOC_ALREADY_EXISTS: "NEXT_DOC_ALREADY_EXISTS",
    INVALID_DOC_STATUS: "INVALID_DOC_STATUS",

    // ---------- REVIEWER ----------
    REVIEWER_NOT_FOUND: "REVIEWER_NOT_FOUND",
    REVIEWER_NOT_PENDING: "REVIEWER_NOT_PENDING",
    REVIEWER_NOT_ACCEPTED: "REVIEWER_NOT_ACCEPTED",
    INVALID_REVIEWER: "INVALID_REVIEWER",
    INVALID_REVIEWER_WEIGHT: "INVALID_REVIEWER_WEIGHT",
    REVIEWER_ALREADY_EXISTS: "REVIEWER_ALREADY_EXISTS",

    // ---------- RESULT ----------
    RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
    RESULT_ALREADY_EXISTS: "RESULT_ALREADY_EXISTS",

    // ---------- PROJECT ----------
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_REJECTED: "PROJECT_REJECTED",
    INVALID_PROJECT_STATUS: "INVALID_PROJECT_STATUS",
    PROJECT_NOT_GRANTED: "PROJECT_NOT_GRANTED",
    PROJECT_NOT_IN_NEGOTIATION: "PROJECT_NOT_IN_NEGOTIATION",

    // ---------- COLLABORATOR ----------
    COLLABORATOR_NOT_FOUND: "COLLABORATOR_NOT_FOUND",
    COLLABORATOR_ALREADY_EXISTS: "COLLABORATOR_ALREADY_EXISTS",
    COLLABORATOR_NOT_PENDING: "COLLABORATOR_NOT_PENDING",

    // ---------- PROJECT_THEME ----------
    PROJECT_THEME_NOT_FOUND: "PROJECT_THEME_NOT_FOUND",
    PROJECT_THEME_ALREADY_EXISTS: "PROJECT_THEME_ALREADY_EXISTS",

    // ---------- PHASE ----------
    PHASE_NOT_FOUND: "PHASE_NOT_FOUND",
    PHASE_NOT_ACTIVE: "PHASE_NOT_ACTIVE",
    PHASE_NOT_PROPOSED: "PHASE_NOT_PROPOSED",
    PHASE_ALREADY_EXISTS: "PHASE_ALREADY_EXISTS",

    // ---------- PHASE_DOCUMENT ----------
    PHASE_DOCUMENT_NOT_FOUND: "PHASE_DOCUMENT_NOT_FOUND"

};

export type ErrorCode =
    typeof ERROR_CODES[keyof typeof ERROR_CODES];