export const ERROR_CODES = {
    //---------- GENERAL --------------  
    // Authentication  
    UNAUTHORIZED: "UNAUTHORIZED",
    TOKEN_MISSING: "TOKEN_MISSING",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    // Authorization
    FORBIDDEN: "FORBIDDEN",
    //Account
    ACCOUNT_PENDING: "ACCOUNT_PENDING",
    INVALID_COMPOSITION: "INVALID_COMPOSITION",
    INVALID_CONSTRAINT: "INVALID_CONSTRAINT",
}